"""
Django settings for realestate_portal project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# realestate_portal/settings.py

import os
from dotenv import load_dotenv # 💡 Ensure aapne pip install python-dotenv kiya hai



# 1. .env file ko load karein
load_dotenv() 

# 2. Variables ko os.getenv() se access karein
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+1)ktl97*(^9lsx!z@s4s00d&76a3t+gej!h5+u@#ic!1bba6q'

# SECURITY WARNING: don't run with debug turned on in production!

# DEBUG ko handle karne ke liye (string se boolean mein convert karna)
DEBUG = os.getenv('DEBUG', 'False') == 'True' 

# Example usage for ALLOWED_HOSTS (optional)
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1').split(',')
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# realestate_portal/settings.py

# ... (at the very bottom)
AUTH_USER_MODEL = 'user.CustomUser'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
import os
DEBUG = os.getenv('DEBUG', 'False') == 'True' 

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # 👈 Add this at the TOP

    'mptt', # <-- Add this
    'ckeditor',
    'ckeditor_uploader',
    'multiselectfield',
    'django.contrib.sites', # Required for sitemap framework
    'django.contrib.sitemaps', # Sitemap app
    'django.contrib.humanize',  # <-- FIX: Add this line



    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
# 📌 My Apps
    'home',
    'projects',
    'properties', # <-- New
    'utility',    # <-- New
    'crm',        # <-- New
    'user',       # <-- New
    'blog',       # <-- New
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]


DEBUG = True

ALLOWED_HOSTS = []


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



ROOT_URLCONF = 'realestate_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         # ... (other keys)
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # <-- Update this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 📌 NEW: Register our global context processor
                'utility.context_processors.global_settings_processor', 
            ],
        },
    },
]

WSGI_APPLICATION = 'realestate_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# 📁 Static files configuration
STATIC_URL = '/static/'

# 🧠 This is where Django will *collect* all static files when you run `collectstatic`
STATIC_ROOT = BASE_DIR / 'staticfiles'   # or os.path.join(BASE_DIR, 'staticfiles')

# 🧱 These are the extra directories Django will look into for static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',   # e.g. your app-level or project-level static folder
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# realestate_portal/settings.py

# ... (Existing settings)

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Static files ko project level par organize karne ke liye
import os # Ensure 'import os' is at the top of the file

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]



# 📌 Media Configuration (For User Uploaded Files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Project root mein 'media' folder banega

# ... (Rest of the settings)


# realestate_portal/settings.py

# ... (End of file ke paas add karein)

# Redirect URLs for authentication
# User login hone ke baad kahan jaye:
LOGIN_REDIRECT_URL = '/'  # Home page
# User login karne se pehle kahan jaye (Agar kisi protected page ko access kare):
LOGIN_URL = '/accounts/login/' 

# Messages Framework ko use karne ke liye (Optional, but good practice for bootstrap classes)
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CKEDITOR_UPLOAD_PATH = "uploads/"

# realestate_portal/settings.py
SITE_ID = 1