# Generated by Django 5.2.7 on 2025-10-16 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_youtube_embed_id'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankoffer',
            name='bank_approval',
        ),
        migrations.RemoveField(
            model_name='bankoffer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bankoffer',
            name='title',
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_offers', to='utility.bank'),
            preserve_default=False,
        ),
    ]
