# Generated by Django 5.2.7 on 2025-10-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_bankoffer_bank_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='google_map',
        ),
    ]
