# Generated by Django 5.2.7 on 2025-10-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_map_iframe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
