# Generated by Django 5.2.7 on 2025-10-30 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_google_map_iframe_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('contacted_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Enquiry',
                'verbose_name_plural': '3. Project Enquiries',
                'ordering': ['-contacted_on'],
            },
        ),
    ]
