# Generated by Django 5.2.7 on 2026-03-06 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0014_project_target_possession_month_and_more'),
        ('rent_utility', '0001_initial'),
        ('utility', '0005_category_sub_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('super_area', models.PositiveIntegerField(help_text='Area in Sq.ft')),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_by', models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Builder', 'Builder'), ('Dealer', 'Dealer'), ('Feature Dealer', 'Feature Dealer')], default='Owner', max_length=20, null=True)),
                ('available_from', models.CharField(blank=True, choices=[('Any Time', 'Any Time'), ('Immediately', 'Immediately'), ('Within 15 Days', 'Within 15 Days'), ('Within 1 Month', 'Within 1 Month'), ('Within 3 Months', 'Within 3 Months'), ('After 3 Months', 'After 3 Months')], default='Any Time', max_length=30)),
                ('age_of_property', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('google_map_iframe', models.TextField(blank=True, null=True)),
                ('youtube_embed_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='YouTube Video ID')),
                ('featured_property', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='banner_img/')),
                ('master_plan', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('furnishing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_utility.furnishingitem')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.locality')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_properties', to='projects.project')),
                ('tenant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_utility.tenanttype')),
            ],
        ),
        migrations.CreateModel(
            name='RentalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='rent.rentalproperty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='rent.rentalproperty')),
            ],
        ),
        migrations.CreateModel(
            name='RentalConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=50)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectivities', to='rent.rentalproperty')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('owner_type', models.CharField(choices=[('Individual', 'Individual Owner'), ('Dealer', 'Property Dealer')], default='Individual', max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('locality', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='owners/')),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_details', to='rent.rentalproperty')),
            ],
        ),
        migrations.CreateModel(
            name='AboutProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(blank=True, max_length=255, null=True)),
                ('about_description', models.TextField(blank=True, null=True)),
                ('about_readmore', models.TextField(blank=True, null=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_section', to='rent.rentalproperty')),
            ],
        ),
        migrations.CreateModel(
            name='RentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_from', models.DateField()),
                ('preferred_tenant', models.CharField(choices=[('Family', 'Family'), ('Bachelors', 'Bachelors'), ('Family/Bachelors', 'Family / Bachelors')], max_length=30)),
                ('lease_duration', models.PositiveIntegerField(help_text='In Months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_details', to='rent.rentalproperty')),
            ],
        ),
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='rent.rentalproperty')),
            ],
        ),
        migrations.CreateModel(
            name='RentalFurnishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_utility.furnishingitem')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnishings', to='rent.rentalproperty')),
            ],
            options={
                'unique_together': {('rental', 'item')},
            },
        ),
        migrations.CreateModel(
            name='RentalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_utility.facility')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='rent.rentalproperty')),
            ],
            options={
                'unique_together': {('rental', 'facility')},
            },
        ),
        migrations.CreateModel(
            name='RentalAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_amenity_items', to='utility.propertyamenities')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rent.rentalproperty')),
            ],
            options={
                'unique_together': {('rental', 'amenity')},
            },
        ),
    ]
