# Generated by Django 5.2.7 on 2026-03-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rentalgallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalgallery',
            old_name='image',
            new_name='galleryimage',
        ),
    ]
