# Generated by Django 5.2.7 on 2026-03-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rename_image_rentalgallery_galleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalGallery',
        ),
    ]
