# Generated by Django 5.2.7 on 2026-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_setting_googletagmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='setting',
            name='googletagmanager',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
