# Generated by Django 5.2.7 on 2025-10-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectamenities',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='amenities/'),
        ),
        migrations.AddField(
            model_name='projectamenities',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='amenities/'),
        ),
    ]
