# Generated by Django 5.2.7 on 2025-10-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_projectamenities_image3_projectamenities_image4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectamenities',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='projectamenities',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='projectamenities',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='projectamenities',
            name='image4',
        ),
    ]
