# Generated by Django 5.2.7 on 2025-10-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_rename_image1_projectamenities_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name_plural': 'Localities'},
        ),
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together={('city', 'name')},
        ),
    ]
