# Generated by Django 5.2.7 on 2025-10-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_alter_locality_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='property/amenities/')),
            ],
            options={
                'verbose_name_plural': 'Property Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
